Repository surendratalk/portfolio-website, pull requests merged in 2022-10, with the labels that each got.

#1 Added form and submit button in index.html
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#3 Create blog.html
  blog.html
Labels: help wanted, hacktoberfest, hacktoberfest-accepted

#4 Create john-doe.html
  john-doe.html
Labels: help wanted, hacktoberfest, hacktoberfest-accepted

#5 Create whitepage.html
  whitepage.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#9 Create inshock.html
  inshock.html
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#8 update option for live preview
  README.md
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#7 Added another price table in the pricing section
  john-doe.html
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#11 Create myart.html
  myart.html
Labels: help wanted, hacktoberfest, hacktoberfest-accepted

#14 Added code of conduct
  CODE_OF_CONDUCT.md
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#12 enhanced the portfolio site
  portfolio site/src/components/about/About.js
  portfolio site/src/components/bio/Bio.js
  portfolio site/src/components/home/Home.js
  portfolio site/src/components/navbar/Navbar.js
  portfolio site/src/components/projects/MyProject.css
  portfolio site/src/components/projects/MyProjects.js
  portfolio site/src/images/vector-1.png
  portfolio site/src/images/vector-2.png
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#16 Create metaverse.html
  metaverse.html
Labels: hacktoberfest, hacktoberfest-accepted
